language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: .travis/build.sh
notifications:
  webhooks:
    urls:
    - https://webhook.atomist.com/travis
    on_success: always
    on_failure: always
    on_start: always
    on_cancel: always
    on_error: always
env:
  global:
  - secure: F8DSbw/22QEzLOYrm0NdbSI3HFaLqUAgpTs5+9PDmqb5f2cOd+hlqR7IS27L1X6KoSFACQdaf6Jp3JOhzsDMFgWu6303Qb7KWgec2CJt0E7CaUF5bUzJTPnYyQpj+IU8qGokITyoWiA8atWQxKz1BipURJBGgdCZkQAeWVcfcdA/k5Evb3G8MqTlZGOOJ4AN3qrroeJM9KneCTKDq5uOt7Jrpo64yeH44G5gp078TQK2Z5pMzfbRHZ8ft1baA+Wbla0neWFBMsRLTHPMDtTw4MV3JlEQPhYl9qRjpy2kGf6jBhal6LLQzW/753M0dCP7d+xZY6+jugaN9X2OhFUKKCoxWFW1dD1Ta09CqMdOmkSpIW7TbHquZo6EeK2iPh0BNRQUkKr9kcD9wlyW+6qhyCKBSU39y53ee1O3QiEzR3+9Jy14ZeEsDUQRvg6638uXRrZvn7THZo2I7MlaMWfR5CQhukTvc+MTkefo2/ulpLeqx2t3oHazK06qPV8Axnj1sDd/zPavIrwWQGkh38ibFF+8QwHSzrsMaYWocYUPdZnE5H3+uHefSSeQRcViHEakW1LAY5JqY4gTXU9YkTgqdIypZG5gwW94a/US0PX+8eYpR0QhSk/2uw10kpfTVtYz/ggz0dSLvG9KXLq67BXbxCUtxdcgnyWLlPRVw1uNvXc=
  - secure: mxVrzZuFEgB8rhXkTT6TlEgzgfHaSArpH6ohpX4eSklYYO9BAvi96IYfEt0tG8+xyl42h4wS09336nG6F+mSK66qJp0Pk66E6a/wjE0TaBnKjRjnHKXMCkf4efWX+jPHKtDmK+H1Dlg8px9c+y8OvdlGDRtvKBAzjpYpdUHtnjHOfqIn7yrAP7KQHqYIYvsEiVPRkhmM+0COtOU1TEdr5S2TkPsEZ/BbOV/xIJkUuwEYMglWO1s+raEuewS8Sg/zOSiYVdjOERDlJMk6THSwI6H5BvG6fASPaxLux+nJoVY48bcy57xHLPQSBEiAQ/b08cqtRMWjUygerGdxEjExzFsDAYTuPcPUI+tw2Eg7pjKofu7p0dxD8v76yZRcKLG93OV1u2dluh/Fr1K7Yn7YSHvJU0OMFtUjWpfjeUNWXAALhex/aj/vsNg73eiAe9ecXSh44yf03UdWyz87dys0384pkmZtn/V36Up/Bve6OFgktv/1OQsRnVJULW+xuQ0nb9XqxWblFKNXivDD6eXnNMP2EXS6a6AKwJ/BltrpQk5s4WcEok9Gc9kFxZFS9YihqLz2qkPx/uX9+0HxuBlmktukH/AiGS3yNW8+AYuHzkLyz9cwoDN0Qww5xg6yjh4hyayX6JzaOWUMMwZGtUEkOR3+Jy6mremmUb728D3pgvE=
  - secure: NS2jyoMlDWhUi72WmN708wi+3IsqD2MLHnzrP+mVcypO4puZTvUT6QROo6HHfOR+UN4MzOuCvMPOOy2W4SuULdySYn2cNK6pYLUF/GxAwdff3ENGmTxNAAXtOj6DOJSEYNx9G+h1gi5hU5Gau23j8uYZD/70e9PkwNphTg+1+YR7AoM/iEKNaGlvXKJG3bOVxOd2fowYeMqBIBVbddBTC0oQjPj1KQ+51km1AntPWfxYQ5dApyIe0uZQV5CZcoUH1FIakTiUAsAjIYCDUzqeWvEjWqHVIRJxNuOQysiBFwibSScZARc8CJ09PjpmEkTxqUKq2uzCpG9fmOTAmdE1tgjCqjzKwHEvFxgg2OFJH9O1YaQJ0RmJ1Iy9blit4jzSiZGer+SRUwxsWeu84ei+S6GC5MhlYigNUJuYHeuq8rxU6M6xnIu7QeD0cGjnsZNtTD9I9U3zQaF7s4BHi/RYfyzDU/kd3D8b/vESFpHRS/gTy0QQpwkWiehyJ13CZeF/D3Fgabc7fJIF3lKsLvyq2FSEIEMCRQRMVCfde46QGjiVUSpduXmH3tBllIWzmNNBdhwudOUGytTR3hDg5X7phVRIBQFzjOeIpPWGJiF1MOUa8aEXi0t+lbS0uo3Qeh2H2dW0rtNXdOocr4ZclglPIJ5Max7kA4bUV4x7tY5u0oo=
